TI_XXWARE_PATH = lib/cc13xxware

CONTIKI_CPU_SOURCEFILES += smartrf-settings.c prop-mode.c prop-mode-tx-power.c cc13xx-50kbps-tsch.c

CFLAGS += -DCPU_FAMILY_CC13X0=1 -DCPU_FAMILY_CC13XX=1
# need by coreSDK DeviceFamily.h evaluations
CFLAGS += -DDeviceFamily_CC13X0 -DDEVICE_LINE_CC13XX
SUBFAMILY        ?=cc13x0-cc26x0

include $(CONTIKI_CPU)/Makefile.cc13x0-cc26x0
include $(CONTIKI_CPU)/Makefile.cc26xx-cc13xx
