//*********************************************************************************
// Generated by SmartRF Studio version 2.10.0 (build#106)
// Compatible with SimpleLink SDK version: CC26x2 SDK 2.20.xx.xx
// Device: CC2652R Rev. 1.1 (Rev. C)
// 
//*********************************************************************************


//*********************************************************************************
// Parameter summary
// Adv. Address: 010203040506 
// Adv. Data: dummy 
// BLE Channel: 17 
// Extended Header: 09 09 010203040506 babe 
// Frequency: 2440 MHz
// PDU Payload length:: 30 
// TX Power: 5 dBm 
// Whitening: true 

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ble_cmd.h)
#include <ti/drivers/rf/RF.h>
#include DeviceFamily_constructPath(rf_patches/rf_patch_cpe_bt5.h)
#include DeviceFamily_constructPath(rf_patches/rf_patch_rfe_bt5.h)
#include DeviceFamily_constructPath(rf_patches/rf_patch_mce_bt5.h)
#include "ble-settings.h"


// TI-RTOS RF Mode Object
RF_Mode RF_prop =
{
    .rfMode = RF_MODE_AUTO,
    .cpePatchFxn = &rf_patch_cpe_bt5,
    .mcePatchFxn = &rf_patch_mce_bt5,
    .rfePatchFxn = &rf_patch_rfe_bt5,
};

// TX Power table
// The RF_TxPowerTable_DEFAULT_PA_ENTRY macro is defined in RF.h and requires the following arguments:
// RF_TxPowerTable_DEFAULT_PA_ENTRY(bias, gain, boost coefficient)
// See the Technical Reference Manual for further details about the "txPower" Command field.
// The PA settings require the CCFG_FORCE_VDDR_HH = 0 unless stated otherwise.
RF_TxPowerTable_Entry txPowerTable[TX_POWER_TABLE_SIZE] = 
{ 
    {-21, RF_TxPowerTable_DEFAULT_PA_ENTRY(7, 3, 0, 3) },
    {-18, RF_TxPowerTable_DEFAULT_PA_ENTRY(9, 3, 0, 3) },
    {-15, RF_TxPowerTable_DEFAULT_PA_ENTRY(8, 2, 0, 6) },
    {-12, RF_TxPowerTable_DEFAULT_PA_ENTRY(10, 2, 0, 8) },
    {-10, RF_TxPowerTable_DEFAULT_PA_ENTRY(12, 2, 0, 11) },
    {-9, RF_TxPowerTable_DEFAULT_PA_ENTRY(13, 2, 0, 5) },
    {-6, RF_TxPowerTable_DEFAULT_PA_ENTRY(13, 1, 0, 16) },
    {-5, RF_TxPowerTable_DEFAULT_PA_ENTRY(14, 1, 0, 17) },
    {-3, RF_TxPowerTable_DEFAULT_PA_ENTRY(17, 1, 0, 20) },
    {0, RF_TxPowerTable_DEFAULT_PA_ENTRY(25, 1, 0, 26) },
    {1, RF_TxPowerTable_DEFAULT_PA_ENTRY(28, 1, 0, 28) },
    {2, RF_TxPowerTable_DEFAULT_PA_ENTRY(13, 0, 0, 34) },
    {3, RF_TxPowerTable_DEFAULT_PA_ENTRY(17, 0, 0, 42) },
    {4, RF_TxPowerTable_DEFAULT_PA_ENTRY(22, 0, 0, 54) },
    {5, RF_TxPowerTable_DEFAULT_PA_ENTRY(30, 0, 0, 74) },
    RF_TxPowerTable_TERMINATION_ENTRY
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverridesCommon[] =
{
    // override_ble5_setup_override_common.xml
    // Synth: Use 48 MHz crystal, enable extra PLL filtering
    (uint32_t)0x02400403,
    // Synth: Configure extra PLL filtering
    (uint32_t)0x001C8473,
    // Synth: Configure synth hardware
    (uint32_t)0x00088433,
    // Synth: Set minimum RTRIM to 3
    (uint32_t)0x00038793,
    // Synth: Configure faster calibration
    HW32_ARRAY_OVERRIDE(0x4004,1),
    // Synth: Configure faster calibration
    (uint32_t)0x1C0C0618,
    // Synth: Configure faster calibration
    (uint32_t)0xC00401A1,
    // Synth: Configure faster calibration
    (uint32_t)0x00010101,
    // Synth: Configure faster calibration
    (uint32_t)0xC0040141,
    // Synth: Configure faster calibration
    (uint32_t)0x00214AD3,
    // Synth: Decrease synth programming time-out (0x0298 RAT ticks = 166 us)
    (uint32_t)0x02980243,
    // DC/DC regulator: In Tx, use DCDCCTL5[3:0]=0xC (DITHER_EN=1 and IPEAK=4). In Rx, use DCDCCTL5[3:0]=0xC (DITHER_EN=1 and IPEAK=4).
    (uint32_t)0xFCFC08C3,
    // Rx: Set LNA bias current offset to adjust +3 (default: 0)
    (uint32_t)0x00038883,
    // Rx: Set RSSI offset to adjust reported RSSI by -2 dB (default: 0)
    (uint32_t)0x000288A3,
    // Bluetooth 5: Compensate for reduced pilot tone length
    (uint32_t)0x01080263,
    // Bluetooth 5: Compensate for reduced pilot tone length
    (uint32_t)0x08E90AA3,
    // Bluetooth 5: Compensate for reduced pilot tone length
    (uint32_t)0x00068BA3,
    // Bluetooth 5: Set correct total clock accuracy for received AuxPtr assuming local sleep clock of 50 ppm
    (uint32_t)0x0E490C83,
    // override_frontend_id.xml
    (uint32_t)0xFFFFFFFF,
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverrides1Mbps[] =
{
    // override_ble5_setup_override_1mbps.xml
    // PHY: Use MCE RAM patch (mode 0), RFE RAM patch (mode 0)
    MCE_RFE_OVERRIDE(1,0,0,1,0,0),
    // Bluetooth 5: Reduce pilot tone length
    HW_REG_OVERRIDE(0x5320,0x0240),
    // Bluetooth 5: Compensate for reduced pilot tone length
    (uint32_t)0x013302A3,
    (uint32_t)0xFFFFFFFF,
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverrides2Mbps[] =
{
    // override_ble5_setup_override_2mbps.xml
    // PHY: Use MCE RAM patch (mode 2), RFE RAM patch (mode 2)
    MCE_RFE_OVERRIDE(1,0,2,1,0,2),
    // Bluetooth 5: Reduce pilot tone length
    HW_REG_OVERRIDE(0x5320,0x0240),
    // Bluetooth 5: Compensate for reduced pilot tone length
    (uint32_t)0x00D102A3,
    (uint32_t)0xFFFFFFFF,
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverridesCoded[] =
{
    // override_ble5_setup_override_coded.xml
    // PHY: Use MCE RAM patch (mode 1), RFE RAM patch (mode 1)
    MCE_RFE_OVERRIDE(1,0,1,1,0,1),
    // Bluetooth 5: Reduce pilot tone length
    HW_REG_OVERRIDE(0x5320,0x0240),
    // Bluetooth 5: Compensate for reduced pilot tone length
    (uint32_t)0x078902A3,
    (uint32_t)0xFFFFFFFF,
};


// CMD_BLE5_RADIO_SETUP
// Bluetooth 5 Radio Setup Command for all PHYs
rfc_CMD_BLE5_RADIO_SETUP_t RF_cmdBle5RadioSetup =
{
    .commandNo = 0x1820,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .defaultPhy.mainMode = 0x0,
    .defaultPhy.coding = 0x0,
    .loDivider = 0x00,
    .config.frontEndMode = 0x0,
    .config.biasMode = 0x0,
    .config.analogCfgMode = 0x0,
    .config.bNoFsPowerUp = 0x0,
    .txPower = 0x941E,
    .pRegOverrideCommon = pOverridesCommon,
    .pRegOverride1Mbps = pOverrides1Mbps,
    .pRegOverride2Mbps = pOverrides2Mbps,
    .pRegOverrideCoded = pOverridesCoded,
};

// CMD_FS
// Frequency Synthesizer Programming Command
rfc_CMD_FS_t RF_cmdFs =
{
    .commandNo = 0x0803,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .frequency = 0x0988,
    .fractFreq = 0x0000,
    .synthConf.bTxMode = 0x0,
    .synthConf.refFreq = 0x0,
    .__dummy0 = 0x00,
    .__dummy1 = 0x00,
    .__dummy2 = 0x00,
    .__dummy3 = 0x0000,
};

// Structure for CMD_BLE5_ADV_AUX.pParams
rfc_ble5AdvAuxPar_t ble5AdvAuxPar =
{
    .pRxQ = 0, // INSERT APPLICABLE POINTER: (dataQueue_t*)&xxx
    .rxConfig.bAutoFlushIgnored = 0x0,
    .rxConfig.bAutoFlushCrcErr = 0x0,
    .rxConfig.bAutoFlushEmpty = 0x0,
    .rxConfig.bIncludeLenByte = 0x0,
    .rxConfig.bIncludeCrc = 0x0,
    .rxConfig.bAppendRssi = 0x0,
    .rxConfig.bAppendStatus = 0x0,
    .rxConfig.bAppendTimestamp = 0x0,
    .advConfig.advFilterPolicy = 0x0,
    .advConfig.deviceAddrType = 0x0,
    .advConfig.targetAddrType = 0x0,
    .advConfig.bStrictLenFilter = 0x0,
    .advConfig.bDirected = 0x0,
    .advConfig.privIgnMode = 0x0,
    .advConfig.rpaMode = 0x0,
    .__dummy0 = 0x00,
    .auxPtrTargetType = 0x00,
    .auxPtrTargetTime = 0x00000000,
    .pAdvPkt = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .pRspPkt = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .pDeviceAddress = 0, // INSERT APPLICABLE POINTER: (uint16_t*)&xxx
    .pWhiteList = 0, // INSERT APPLICABLE POINTER: (uint32_t*)&xxx
};

// CMD_BLE5_ADV_AUX
// Bluetooth 5 Secondary Channel Advertiser Command
rfc_CMD_BLE5_ADV_AUX_t RF_cmdBle5AdvAux =
{
    .commandNo = 0x1824,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .channel = 0x8C,
    .whitening.init = 0x51,
    .whitening.bOverride = 0x1,
    .phyMode.mainMode = 0x0,
    .phyMode.coding = 0x0,
    .rangeDelay = 0x00,
    .txPower = 0x0000,
    .pParams = &ble5AdvAuxPar,
    .pOutput = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .tx20Power = 0x00000000,
};

// Structure for CMD_BLE5_GENERIC_RX.pParams
rfc_bleGenericRxPar_t bleGenericRxPar =
{
    .pRxQ = 0, // INSERT APPLICABLE POINTER: (dataQueue_t*)&xxx
    .rxConfig.bAutoFlushIgnored = 0x0,
    .rxConfig.bAutoFlushCrcErr = 0x0,
    .rxConfig.bAutoFlushEmpty = 0x0,
    .rxConfig.bIncludeLenByte = 0x1,
    .rxConfig.bIncludeCrc = 0x1,
    .rxConfig.bAppendRssi = 0x1,
    .rxConfig.bAppendStatus = 0x1,
    .rxConfig.bAppendTimestamp = 0x0,
    .bRepeat = 0x01,
    .__dummy0 = 0x0000,
    .accessAddress = 0x8E89BED6,
    .crcInit0 = 0x55,
    .crcInit1 = 0x55,
    .crcInit2 = 0x55,
    .endTrigger.triggerType = 0x1,
    .endTrigger.bEnaCmd = 0x0,
    .endTrigger.triggerNo = 0x0,
    .endTrigger.pastTrig = 0x0,
    .endTime = 0x00000001,
};

// CMD_BLE5_GENERIC_RX
// Bluetooth 5 Generic Receiver Command
rfc_CMD_BLE5_GENERIC_RX_t RF_cmdBle5GenericRx =
{
    .commandNo = 0x1829,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .channel = 0x8C,
    .whitening.init = 0x51,
    .whitening.bOverride = 0x1,
    .phyMode.mainMode = 0x0,
    .phyMode.coding = 0x0,
    .rangeDelay = 0x00,
    .txPower = 0x0000,
    .pParams = &bleGenericRxPar,
    .pOutput = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .tx20Power = 0x00000000,
};
