MOTELIST_ZOLERTIA := RE-Mote
BOARD_SOURCEFILES += board.c antenna-sw.c mmc-arch.c rtcc.c power-mgmt.c

MODULES += $(CONTIKI_NG_LIB_DIR)/fs/fat $(CONTIKI_NG_LIB_DIR)/fs/fat/option
MODULES += $(CONTIKI_NG_ARCH_PLATFORM_DIR)/$(TARGET)/fs/fat
MODULES += $(CONTIKI_NG_DRIVERS_DIR)/disk/mmc
