MOTELIST_ZOLERTIA = remote
BOARD_SOURCEFILES += board.c antenna-sw.c mmc-arch.c rtcc.c leds-res-arch.c power-mgmt.c

MODULES += core/lib/fs/fat core/lib/fs/fat/option arch/platform/zoul/fs/fat arch/dev/disk/mmc
