CONTIKI_PROJECT      = sixp-node.c
PROJECT_SOURCEFILES += test-sf.c

CONTIKI  = ../../../

MAKE_MAC = MAKE_MAC_TSCH
MAKE_ROUTING = MAKE_ROUTING_NONE
MODULES += os/net/mac/tsch/sixtop

include $(CONTIKI)/Makefile.include
