
SDK_DRIVERLIB_BIN := $(SDK_DRIVERLIB)/bin/gcc

ifeq "$(SIMPLELINK_DEVICE)" "cc13x2" 
CFLAGS += -DDeviceFamily_CC13X2
else
CFLAGS += -DDeviceFamily_CC26X2
endif

CFLAGS += -I$(CPU_ABS_PATH)/cc26x2_cc13x2

TARGET_LIBFILES += $(SDK_DRIVERLIB_BIN)/driverlib.lib

include $(CONTIKI)/arch/cpu/arm/cortex-m/cm4/Makefile.cm4
