# Validation of device variables
ifndef DEVICE_FAMILY
    $(error DEVICE_FAMILY not defined!)
endif

ifndef DEVICE_OPN
    $(error DEVICE_OPN not defined!)
endif

ifndef RAIL_CPU
    $(error RAIL_CPU not defined!)
endif

ifndef RAIL_FAMILY
    $(error RAIL_FAMILY not defined!)
endif

DEVICE_FAMILY_LOWER = $(shell echo $(DEVICE_FAMILY) | tr A-Z a-z)
DEVICE_OPN_UPPER = $(shell echo $(DEVICE_OPN) | tr a-z A-Z)

# OPN Specific
LDSCRIPT ?= $(CONTIKI_CPU)/$(DEVICE_OPN)/$(DEVICE_FAMILY_LOWER).ld
GSDK_C_SRCS += $(CONTIKI_CPU)/$(DEVICE_OPN)/sl_device_init_clocks.c
GSDK_SRC_PATHS += $(CONTIKI_CPU)/$(DEVICE_OPN)
GSDK_INC_PATHS += $(CONTIKI_CPU)/$(DEVICE_OPN)
GSDK_INC_PATHS += $(CONTIKI_CPU)/$(DEVICE_OPN)/config
GSDK_INC_PATHS += $(CONTIKI_CPU)/config
CFLAGS += -DCPU_CONF_PATH=\"$(DEVICE_OPN)-conf.h\"

# Simplicity SDK

## Device
GSDK_C_SRCS += $(GSDK_ROOT)/platform/Device/SiliconLabs/$(DEVICE_FAMILY)/Source/startup_$(DEVICE_FAMILY_LOWER).c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/Device/SiliconLabs/$(DEVICE_FAMILY)/Source/system_$(DEVICE_FAMILY_LOWER).c
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/Device/SiliconLabs/$(DEVICE_FAMILY)/Include
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/Device/SiliconLabs/$(DEVICE_FAMILY)/Source
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/Device/SiliconLabs/$(DEVICE_FAMILY)/Source/GCC
CFLAGS += -D$(DEVICE_OPN_UPPER)

## hardware
GSDK_C_SRCS += $(GSDK_ROOT)/hardware/board/src/sl_board_init.c
GSDK_C_SRCS += $(GSDK_ROOT)/hardware/board/src/sl_board_control_gpio.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/hardware/board/src
GSDK_INC_PATHS += $(GSDK_ROOT)/hardware/board/inc

## platform
#GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/system/src/sl_system_init.c
#GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/system/src/sl_system_kernel.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/system/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/system/inc

## emlib
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_cmu.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_core.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_emu.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_gpio.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_ldma.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_msc.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_prs.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_rmu.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_system.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_timer.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_usart.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_wdog.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_burtc.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emlib/src/em_eusart.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/emlib/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/emlib/inc

## emdrv

### common
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/emdrv/common/inc

### gpiointerrupt
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emdrv/gpiointerrupt/src/gpiointerrupt.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/emdrv/gpiointerrupt/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/emdrv/gpiointerrupt/inc

### dmadrv
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emdrv/dmadrv/src/dmadrv.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/emdrv/dmadrv/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/emdrv/dmadrv/inc
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/emdrv/dmadrv/inc/s2_signals

### uartdrv
GSDK_C_SRCS += $(GSDK_ROOT)/platform/emdrv/uartdrv/src/uartdrv.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/emdrv/uartdrv/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/emdrv/uartdrv/inc

## peripheral
GSDK_C_SRCS += $(GSDK_ROOT)/platform/peripheral/sl_hal_sysrtc.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/peripheral/sl_hal_gpio.c
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/peripheral/inc
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/peripheral/src

## common
GSDK_C_SRCS += $(GSDK_ROOT)/platform/common/src/sl_slist.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/common/src/sl_string.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/common/src/sl_core_cortexm.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/common/src/sl_assert.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/common/src/sl_syscalls.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/common/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/common/inc
#GSDK_INC_PATHS += $(GSDK_ROOT)/platform/common/config

### toolchain
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/common/toolchain/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/common/toolchain/inc

### driver
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/driver/gpio/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/driver/gpio/inc
GSDK_C_SRCS += $(GSDK_ROOT)/platform/driver/gpio/src/sl_gpio.c

## Service(s)

### sleeptimer
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/sleeptimer/src/sl_sleeptimer.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/sleeptimer/src/sl_sleeptimer_hal_sysrtc.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/sleeptimer/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/sleeptimer/inc

### iostream
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/iostream/src/sl_iostream.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/iostream/src/sl_iostream_usart.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/iostream/src/sl_iostream_uart.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/iostream/src/sl_iostream_stdlib_config.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/iostream/src/sl_iostream_retarget_stdio.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/iostream/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/iostream/inc

### device_manager
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_manager/src/sl_device_clock.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_manager/src/sl_device_peripheral.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/device_manager/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/device_manager/inc
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/device_manager/devices
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg28.c # efr32zg28
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/device_manager/clocks
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_manager/clocks/sl_device_clock_efr32xg28.c           # efr32zg28

### interrupt_manager
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/interrupt_manager/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/interrupt_manager/inc

### device_init
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_init/src/sl_device_init_nvic.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_init/src/sl_device_init_dcdc_s2.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_init/src/sl_device_init_hfxo_s2.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_init/src/sl_device_init_lfxo_s2.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/device_init/src/sl_device_init_emu_s2.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/device_init/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/device_init/inc

### clock_manager
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/clock_manager/sl_clock_manager.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/clock_manager/sl_clock_manager_init.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/clock_manager/sl_clock_manager_hal_s2.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/clock_manager/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/clock_manager/inc

### hfxo_manager
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/hfxo_manager/sl_hfxo_manager.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/hfxo_manager/sl_hfxo_manager_hal_s2.c
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/hfxo_manager/inc
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/hfxo_manager/src

### power_manager
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/power_manager/src/common/sl_power_manager_common.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/power_manager/src/common/sl_power_manager_em4.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/power_manager/src/sleep_loop/sl_power_manager.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/power_manager/src/sleep_loop
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/power_manager/src/common
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/power_manager/inc

### mpu
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/mpu/src/sl_mpu.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/mpu/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/mpu/inc

### memory_manager
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/memory_manager/src/sl_memory_manager_region.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/memory_manager/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/memory_manager/inc

### udelay
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/udelay/src/sl_udelay.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/service/udelay/src/sl_udelay_armv6m_gcc.S
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/service/udelay/src
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/service/udelay/inc

## radio

### rail_lib
GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c
GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/pa-conversions/pa_curves_efr32.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/pa-conversions
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/pa-conversions

GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_dma/sl_rail_util_dma.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_dma
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_callbacks

GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_pti/sl_rail_util_pti.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_pti
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_pti

GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rf_path_switch/sl_rail_util_rf_path_switch.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rf_path_switch
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rf_path_switch

GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rf_path/sl_rail_util_rf_path.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rf_path
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rf_path

GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rssi/sl_rail_util_rssi.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rssi
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_rssi

#GSDK_C_SRCS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_protocol/sl_rail_util_protocol.c
GSDK_SRC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_protocol
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_protocol

GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/plugin/rail_util_callbacks
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/chip/efr32/$(RAIL_FAMILY)
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/common
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/protocol
GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/protocol/ieee802154

#GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/protocol/ble
#GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/protocol/sidewalk
#GSDK_INC_PATHS += $(GSDK_ROOT)/platform/radio/rail_lib/protocol/zwave

LIBRAIL = $(GSDK_ROOT)/platform/radio/rail_lib/autogen/librail_release/librail_$(RAIL_CPU)_gcc_release.a
#LIBRAIL = $(GSDK_ROOT)/platform/radio/rail_lib/autogen/librail_release/librail_module_$(RAIL_CPU)_gcc_release.a
#LIBRAIL = $(GSDK_ROOT)/platform/radio/rail_lib/autogen/librail_release/librail_multiprotocol_module_$(RAIL_CPU)_gcc_release.a
CFLAGS += -DSL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0

CFLAGS += -DDSL_CODE_COMPONENT_CORE=core
CFLAGS += -DSL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager
CFLAGS += -DSL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral
CFLAGS += -DSL_CODE_COMPONENT_DMADRV=dmadrv
CFLAGS += -DSL_CODE_COMPONENT_HAL_COMMON=hal_common
CFLAGS += -DSL_CODE_COMPONENT_HAL_GPIO=hal_gpio
CFLAGS += -DSL_CODE_COMPONENT_HAL_SYSRTC=hal_sysrtc
CFLAGS += -DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer
CFLAGS += -DSL_CODE_COMPONENT_POWER_MANAGER=power_manager

CFLAGS += -DSL_COMPONENT_CATALOG_PRESENT=1 
CFLAGS += -DSL_CATALOG_GPIO_PRESENT=1
CFLAGS += -DSL_CLOCK_MANAGER_AUTO_BAND_VALID=1
#CFLAGS += -DCMSIS_NVIC_VIRTUAL=1 -DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"
CFLAGS += '-DSL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>'
#CFLAGS += -DNDEBUG=1 -DNO_DEBUGPRINT=1

# Contiki

## CPU-dependent directories
CONTIKI_CPU_DIRS += .
CONTIKI_CPU_DIRS += sys
CONTIKI_CPU_DIRS += dev
CONTIKI_CPU_DIRS += os
CONTIKI_CPU_DIRS += common
CONTIKI_CPU_DIRS += storage

## CPU-dependent source files

### dev
CONTIKI_CPU_SOURCEFILES += gpio-hal-arch.c
CONTIKI_CPU_SOURCEFILES += uart-arch.c
CONTIKI_CPU_SOURCEFILES += watchdog-arch.c

### radio
CONTIKI_CPU_SOURCEFILES += efr32-radio-IEEE802154_2p4GHz.c
#CONTIKI_CPU_SOURCEFILES += sl_rail_util_callbacks.c
CONTIKI_CPU_SOURCEFILES += efr32-radio-buffer.c

### sys
CONTIKI_CPU_SOURCEFILES += rtimer-arch.c
CONTIKI_CPU_SOURCEFILES += clock-arch.c
CONTIKI_CPU_SOURCEFILES += int-master-arch.c
CONTIKI_CPU_SOURCEFILES += linkaddr-arch.c

### os
CONTIKI_CPU_SOURCEFILES += dbg-arch.c
CONTIKI_CPU_SOURCEFILES += random-arch.c

### storage
CONTIKI_CPU_SOURCEFILES += cfs-coffee-arch.c

### common
CONTIKI_CPU_SOURCEFILES += sl_uartdrv_init.c

ifeq ($(CLANG),0)
  LDFLAGS += --specs=nosys.specs
endif
LDFLAGS += -Wl,--defsym=_stack=__StackLimit
LDFLAGS += -Wl,--defsym=_stack_origin=__StackTop
LDFLAGS += -Wl,--defsym=_heap=__HeapBase
LDFLAGS += -Wl,--defsym=_eheap=__HeapLimit

TARGET_LIBFILES += -lgcc -lc -lnosys

CONTIKI_SOURCEFILES += $(CONTIKI_CPU_SOURCEFILES)
CONTIKI_SOURCEFILES += $(notdir $(GSDK_C_SRCS))
CONTIKI_SOURCEFILES += $(notdir $(GSDK_ASM_SRCS))

EXTERNALDIRS += $(GSDK_INC_PATHS)
EXTERNALDIRS += $(GSDK_SRC_PATHS)

CONTIKI_OBJECTFILES += $(LIBRAIL)

