CFLAGS += -imacros native/module-macros.h
MODULES += os/services/slip-cmd

MAKE_MAC = MAKE_MAC_OTHER
MAKE_NET = MAKE_NET_IPV6

PREFIX ?= fd00::1/64
connect-router:	border-router.native
	sudo ./border-router.native $(PREFIX)
