CONTIKI_PROJECT += test-bmp180 test-grove-light-sensor

CONTIKI_TARGET_SOURCEFILES += bmp180.c adc-sensors.c

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = oppila

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
