################################################################################
# SimpleLink LaunchPad makefile

DEFINES += BOARD_LAUNCHPAD=1

# leds-arch.c/h etc.
BOARD_SOURCEFILES += launchpad-sensors.c button-sensor-arch.c leds-arch.c

CONTIKI_TARGET_DIRS += launchpad

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=0
