CONTIKI_PROJECT =  test-ldr-sensor test-bmp180 test-adxl345

CONTIKI_TARGET_SOURCEFILES += bmp180.c adc-sensors.c adxl345.c

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = owinos

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
