################################################################################
# SimpleLink Device makefile

SUBFAMILY = cc13x0-cc26x0
DEVICE_FAMILY = CC13X0

BOARD_SOURCEFILES += CC1350_LAUNCHXL_433.c

SUPPORTS_PROP_MODE = 1
SUPPORTS_IEEE_MODE = 1

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL = 1

# Include the common board makefile
include $(FAMILY_PATH)/launchpad/Makefile.launchpad
