NRFX_ROOT = $(CONTIKI_CPU)/lib/nrfx

ifeq (,$(wildcard $(NRFX_ROOT)/*))
    $(warning $(NRFX_ROOT) does not exist or is empty.)
    $(warning Did you run 'git submodule update --init' ?)
    $(error "")
endif
