################################################################################
# SimpleLink LaunchPad makefile

DEFINES += BOARD_SMARTRF06EB=1

# leds-arch.c/h etc.
BOARD_SOURCEFILES += srf06-sensors.c button-sensor-arch.c leds-arch.c

CONTIKI_TARGET_DIRS += srf06

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
