#ifndef _BLE-SETTINGS_H_
#define _BLE-SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.10.0 (build#106)
// Compatible with SimpleLink SDK version: CC13x2 SDK 2.20.xx.xx
// Device: CC1352R Rev. 1.1
// 
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ble_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define TX_POWER_TABLE_SIZE 16


// TX Power Table Object
extern RF_TxPowerTable_Entry txPowerTable[TX_POWER_TABLE_SIZE];


// TI-RTOS RF Mode Object
extern RF_Mode RF_prop;


// RF Core API commands
extern rfc_CMD_BLE5_RADIO_SETUP_t RF_cmdBle5RadioSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_BLE5_ADV_AUX_t RF_cmdBle5AdvAux;
extern rfc_CMD_BLE5_GENERIC_RX_t RF_cmdBle5GenericRx;


// RF Core API Overrides
extern uint32_t pOverridesCommon[];
extern uint32_t pOverrides1Mbps[];
extern uint32_t pOverrides2Mbps[];
extern uint32_t pOverridesCoded[];


#endif // _BLE-SETTINGS_H_

