#ifndef _IEEE_SETTINGS_H_
#define _IEEE_SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.9.0 (build#85)
// Compatible with SimpleLink SDK version: CC13x2 SDK 2.10.xx.xx
// Device: CC1352P Rev. 1.1
//
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ieee_cmd.h)

#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode RF_ieeeMode;


// TX Power Table
extern RF_TxPowerTable_Entry defaultPaTxPowerTable[16];
extern RF_TxPowerTable_Entry highPaTxPowerTable[16];


// RF Core API commands
extern rfc_CMD_RADIO_SETUP_t RF_cmdRadioSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_IEEE_TX_t RF_cmdIeeeTx;
extern rfc_CMD_IEEE_RX_t RF_cmdIeeeRx;


// RF Core API Overrides
extern uint32_t pDefaultPaOverrides[];
extern uint32_t pHighPaOverrides[];


#endif // _IEEE_SETTINGS_H_

