# Copyright (c) 2012, Thingsquare, www.thingsquare.com.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the Institute nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

all: clean
	@$(MAKE) summary

ifdef NUMCORES
  # User wants a certain number, respect that.
  CPUS := $(NUMCORES)
else ifneq (, $(shell which nproc))
  # Query the machine for the number of processors.
  CPUS := $(shell nproc)
else
  # Default to something suitable for a mid-range laptop.
  CPUS := 8
endif

# Make tests quiet unless running in CI or user specifies something else.
ifndef CI
  V ?= 1
  Q ?= @
  MAKEOPTIONS ?= V=$(V) Q=$(Q)
endif
PRINT_DIR ?= --no-print-directory
MAKEOPTIONS += $(PRINT_DIR) WERROR=1

# The stuff below is some GNU make magic to automatically make make
# give each compile test a number, prefixed with a 0 if the number is
# < 10, to match the way the simulation tests output works.
nine := x x x x x x x x x
max = $(subst xx,x,$(join ${1},${2}))
gt = $(filter-out $(words ${1}),$(words $(call max,${1},${2})))
addzero = $(if $(call gt,${nine},$(1)),$(words ${1}),0$(words ${1}))
get_target = $(firstword $(subst :, ,$1))
get_target_vars = $(wordlist 2,15,$(subst :, ,$1))

define dooneexample
@echo -n Building example $(3): $(1) $(4) for target $(2)
@((cd $(EXAMPLESDIR)/$(1) && \
   $(MAKE) $(4) TARGET=$(2) $(MAKEOPTIONS) clean && \
   make -j$(CPUS) $(4) TARGET=$(2) $(MAKEOPTIONS)) 2>make.err && \
 (echo " -> OK" && printf "%-75s %-40s %-20s TEST OK\n" "$(1)" "$(4)" "$(2)" > $(3)-$(subst /,-,$(1))$(2).testlog) || \
 (echo " -> FAIL" && printf "%-75s %-40s %-20s TEST FAIL\n" "$(1)" "$(4)" "$(2)" > $(3)-$(subst /,-,$(1))$(2).testlog ; cat make.err))
@rm -f make.err
endef

define doexample
$(eval i+=x)
$(call dooneexample,$(dir $(call get_target,${1})),$(notdir $(call get_target,${1})),$(call addzero,${i}),$(call get_target_vars,${1}))
endef
#end of GNU make magic

examples: | $(EXAMPLESDIR)
	$(foreach ex, $(EXAMPLES), $(call doexample, ${ex}))

$(EXAMPLESDIR):
	@echo "Could not find examples directory $(EXAMPLESDIR).\n"
	@echo "If this failure is when running 19-out-of-tree-builds, clone"
	@echo "https://github.com/contiki-ng/out-of-tree-tests into"
	@echo "$(EXAMPLESDIR) and run the test again.\n"
	@false

summary: examples
	@cat *.testlog > summary
	@echo "========== Summary =========="
	@cat summary

clean: | $(EXAMPLESDIR)
	@rm -f *.testlog summary
	@$(foreach example, $(EXAMPLES), \
           $(foreach target, $(EXAMPLESTARGETS), \
             (cd $(EXAMPLESDIR)/$(example) && $(MAKE) TARGET=$(target) clean);))
