TESTS=$(wildcard ??-*.sh)
TESTLOGS=$(sort $(patsubst %.sh,%.testlog,$(TESTS)))

CONTIKI=../..

all: clean
	@$(MAKE) summary

summary: $(TESTLOGS)
	@cat *.testlog > summary
	@echo "========== Summary =========="
	@cat summary

%.testlog: %.sh
	@echo "========== Running script test $(basename $@).sh =========="
	@./"$(basename $@).sh" "$(realpath $(CONTIKI))"

clean:
	@rm -f *.*log report summary
