TESTS=$(wildcard ??-*.sh)
TESTLOGS=$(sort $(patsubst %.sh,%.testlog,$(TESTS)))

CONTIKI=../..

all: clean
	@$(MAKE) summary

summary: $(TESTLOGS)
	@echo "========== Summary =========="
	@([ ! -f summary ] && echo "All tests OK" && touch summary) || \
          (echo "Failures:" && cat summary && false)

%.testlog: %.sh
	@echo "========== Running script test $(basename $@).sh =========="
	@./"$(basename $@).sh" "$(realpath $(CONTIKI))" || \
          echo "TEST FAIL: $<" >> summary

clean:
	@rm -f *.*log report summary
