#ifndef _BLE-SETTINGS_H_
#define _BLE-SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.10.0 (build#106)
// Compatible with SimpleLink SDK version: No known SDK for this device
// Device: CC2650 Rev. 2.2
// 
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ble_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define TX_POWER_TABLE_SIZE 14


// TX Power Table Object
extern RF_TxPowerTable_Entry txPowerTable[TX_POWER_TABLE_SIZE];


// TI-RTOS RF Mode Object
extern RF_Mode RF_ble;


// RF Core API commands
extern rfc_CMD_RADIO_SETUP_t RF_cmdRadioSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_BLE_ADV_NC_t RF_cmdBleAdvNc;
extern rfc_CMD_BLE_GENERIC_RX_t RF_cmdBleGenericRx;


// RF Core API Overrides
extern uint32_t pOverrides[];


#endif // _BLE-SETTINGS_H_

