DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT=client

all: $(CONTIKI_PROJECT)


MAKE_MAC = 		 MAKE_MAC_BLE
MAKE_NET =     MAKE_NET_IPV6
CONTIKI = ../../..
include $(CONTIKI)/Makefile.include