CONTIKI_PROJECT = test-rtcc

TARGET = zoul

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = zoul
# Only the Re-Mote is equiped with an RTCC
BOARDS_ONLY = remote-reva remote-revb

CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
