DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = very-sleepy-demo

all: $(CONTIKI_PROJECT)

CONTIKI_WITH_IPV6 = 1

MODULES += os/net/app-layer/coap

CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
