# Common Makefile between Z1 and Z1SP

CONTIKI_TARGET_SOURCEFILES += contiki-z1-platform.c 

include $(CONTIKI_NG_RELOC_PLATFORM_DIR)/z1/Makefile.common

ifeq ($(ZOLERTIA_Z1SP),1)
include $(CONTIKI_NG_RELOC_PLATFORM_DIR)/z1/Makefile.z1sp
endif

MODULES += arch/dev/cc2420 os/storage/cfs
