MODULES += os/lib/cbor
MODULES += os/net/security/cose
MODULES += os/net/app-layer/coap
MODULES += os/net/security/micro-ecc
MODULES += os/services/zcbor

ifneq ($(MAKE_EDHOC_METHOD),)
  CFLAGS += -DEDHOC_METHOD=$(MAKE_EDHOC_METHOD)
endif
