################################################################################
# CC13x0/CC26x0 CPU makefile

### Simplelink SDK pre-compiled libraries
TARGET_LIBFILES += $(SDK_KERNEL)/lib/nortos_$(SDK_LIB_NAME).am3g
TARGET_LIBFILES += $(SDK_DRIVERS)/rf/lib/rf_multiMode_$(SDK_LIB_NAME).am3g
TARGET_LIBFILES += $(SDK_DRIVERS)/lib/drivers_$(SDK_LIB_NAME).am3g
TARGET_LIBFILES += $(SDK_DEVICE)/driverlib/bin/gcc/driverlib.lib

include $(CONTIKI)/arch/cpu/arm/cortex-m/cm3/Makefile.cm3
