### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13x2

# need by silmplelink settings defs
CFLAGS += -DDEVICE_CC1352R

### Add to the source dirs
CONTIKI_TARGET_DIRS += launchpad/cc1352

### Include the common launchpad makefile
include $(PLATFORM_ROOT_DIR)/launchpad/Makefile.launchpad
