CONTIKI_PROJECT = test-examples

all: $(CONTIKI_PROJECT)

MODULES += os/services/unit-test

# If you want to add this to tests/ directory, set appropriate CONTIKI path
CONTIKI = ../../../..

include $(CONTIKI)/Makefile.include
