CONTIKI_PROJECT = test-data-structures

all: $(CONTIKI_PROJECT)

MODULES += os/services/unit-test

MAKE_MAC = MAKE_MAC_NULLMAC
MAKE_NET = MAKE_NET_NULLNET

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
