CONTIKI_PROJECT = very-sleepy-demo

PLATFORMS_ONLY = simplelink

all: $(CONTIKI_PROJECT).$(TARGET)

SMALL = 1

MODULES += os/net/app-layer/coap

CONTIKI = ../../../../..
include $(CONTIKI)/Makefile.include
