CONTIKI = ../../..

PLATFORMS_ONLY= cc2538 sky

MODULES += os/services/unit-test
MODULES += os/storage/cfs

CONTIKI_PROJECT = test-cfs test-coffee example-coffee
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
