# $Id: Makefile.sky,v 1.38 2010/05/03 13:51:11 nifi Exp $

CONTIKI_TARGET_SOURCEFILES += contiki-sky-platform.c \
	sht11.c sht11-sensor.c light-sensor.c battery-sensor.c \
	button-sensor.c

include $(CONTIKI_NG_RELOC_PLATFORM_DIR)/sky/Makefile.common

MODULES += $(CONTIKI_NG_DRIVERS_DIR)/cc2420 $(CONTIKI_NG_DRIVERS_DIR)/sht11
MODULES += $(CONTIKI_NG_DRIVERS_DIR)/ds2411 $(CONTIKI_NG_STORAGE_DIR)/cfs
