include $(CONTIKI_CPU)/Makefile.gecko_sdk  

DEVICE_FAMILY := EFR32BG22
RAIL_CPU := efr32xg22
RAIL_FAMILY := efr32xg2x
SL_SERIES := 2

CFLAGS += -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse

LDFLAGS += -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse

include $(CONTIKI_CPU)/Makefile.gecko

include $(CONTIKI)/$(CONTIKI_NG_CM33_DIR)/Makefile.cm33

include $(CONTIKI_CPU)/Makefile.commander
