#!/bin/bash

# Periodically print an invisible character to keep Windows docker from
# terminating the session for inactivity.
/bin/bash -c "while sleep 120; do printf '\33[0n'; done" &
PID=$!

trap exit_cleanup INT

function exit_cleanup() {
  kill $PID
}

ant -e -logger org.apache.tools.ant.listener.SimpleBigProjectLogger -f $HOME/contiki-ng/tools/cooja/build.xml run_bigmem

exit_cleanup
