EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/native \
hello-world/sky \
hello-world/z1 \
eeprom-test/native \
platform-specific/zolertia/z1/z1 \
ipv6/multicast/sky \
sensniff/z1 \

TOOLS=

include ../Makefile.compile-test
