EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/native \
hello-world/sky \
eeprom-test/native \
ipv6/multicast/sky \
logging/native \

TOOLS=

include ../Makefile.compile-test
