#ifndef NRF54L15_TZ_REGION_DEFS_H_
#define NRF54L15_TZ_REGION_DEFS_H_

#include "flash_layout.h"

#define S_HEAP_SIZE             0x00002000u
#define S_MSP_STACK_SIZE_INIT   0x00000400u
#define S_MSP_STACK_SIZE        0x00002000u
#define S_PSP_STACK_SIZE        0x00002000u

#define NS_HEAP_SIZE            0x00002000u
#define NS_MSP_STACK_SIZE       0x00000400u
#define NS_PSP_STACK_SIZE       0x00002000u

#define MPC_FLASH_REGION_SIZE   0x00001000u
#define MPC_SRAM_REGION_SIZE    0x00001000u

#define CMSE_VENEER_REGION_SIZE 0x00001000u

#define S_CODE_START            (S_ROM_ALIAS_BASE)
#define S_CODE_SIZE             (FLASH_S_PARTITION_SIZE)
#define S_CODE_LIMIT            (S_CODE_START + S_CODE_SIZE - 1u)

#define S_DATA_START            (S_RAM_ALIAS_BASE)
#define S_DATA_SIZE             (S_RAM_PARTITION_SIZE)
#define S_DATA_LIMIT            (S_DATA_START + S_DATA_SIZE - 1u)

#define NS_PARTITION_START      (NS_ROM_ALIAS_BASE + NON_SECURE_IMAGE_OFFSET)
#define NS_PARTITION_SIZE       (FLASH_NS_PARTITION_SIZE)

#define NS_CODE_START           (NS_PARTITION_START)
#define NS_CODE_SIZE            (FLASH_NS_PARTITION_SIZE)
#define NS_CODE_LIMIT           (NS_CODE_START + NS_CODE_SIZE - 1u)

#define NS_DATA_START           (NS_RAM_ALIAS_BASE + S_RAM_PARTITION_SIZE)
#define NS_DATA_SIZE            (NS_RAM_PARTITION_SIZE)
#define NS_DATA_LIMIT           (NS_DATA_START + NS_DATA_SIZE - 1u)

#define NSC_REGION_START        (S_CODE_START + FLASH_S_PARTITION_SIZE - CMSE_VENEER_REGION_SIZE)
#define NSC_REGION_LIMIT        (S_CODE_START + FLASH_S_PARTITION_SIZE - 1u)

#endif /* NRF54L15_TZ_REGION_DEFS_H_ */
