EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

# build jn516x examples, covering IPv6, RPL, CoAP
EXAMPLES = \
hello-world/jn516x \
platform-specific/jn516x/dr1175-sensors/jn516x \
platform-specific/jn516x/rpl/node/jn516x \
platform-specific/jn516x/rpl/coap-dongle-node/jn516x \
platform-specific/jn516x/rpl/coap-dr1175-node/jn516x \
platform-specific/jn516x/rpl/coap-dr1199-node/jn516x \
platform-specific/jn516x/tsch/simple-sensor-network/node/jn516x \
platform-specific/jn516x/tsch/tx-power-verification/node/jn516x \
platform-specific/jn516x/tsch/uart1-test-node/jn516x \
coap/coap-example-client/jn516x \
coap/coap-example-server/jn516x \
rpl-border-router/jn516x \
6tisch/simple-node/jn516x \
libs/logging/jn516x \
6tisch/etsi-plugtest-2017/jn516x

TOOLS=

include ../Makefile.compile-test
