CONTIKI_PROJECT = ip64-router
all: $(CONTIKI_PROJECT)

BOARD = orion

CONTIKI = ../../../../..

WITH_IP64 = 1

PROJECT_SOURCEFILES += httpd-simple.c

PLATFORMS_ONLY = zoul
BOARDS_ONLY = orion

include $(CONTIKI)/Makefile.include
