EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx \
platform-specific/cc26xx/very-sleepy-demo/srf06-cc26xx:BOARD=sensortag/cc2650 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=sensortag/cc2650 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=sensortag/cc1350 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=srf06/cc13xx \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc2650 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc1310 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc1350 \
platform-specific/cc26xx/very-sleepy-demo/srf06-cc26xx \
hello-world/cc2538dk \
rpl-border-router/cc2538dk \
rpl-udp/cc2538dk \
coap-example/cc2538dk \
ipso-objects/cc2538dk \
udp-echo-server/cc2538dk \
multicast/cc2538dk \
platform-specific/cc2538-common/cc2538dk \
platform-specific/cc2538-common/mqtt-demo/cc2538dk \
platform-specific/cc2538-common/crypto/cc2538dk \
platform-specific/cc2538-common/pka/cc2538dk \
platform-specific/cc2538-common/zoul \
platform-specific/cc2538-common/mqtt-demo/zoul \
platform-specific/cc2538-common/crypto/zoul \
platform-specific/cc2538-common/pka/zoul \
platform-specific/zoul/orion/ip64-router/zoul:BOARD=orion \
coap-example/zoul \
ipso-objects/zoul \
hello-world/zoul \
sensniff/cc2538dk \
sensniff/openmote-cc2538 \
sensniff/zoul \
sensniff/zoul:ZOUL_CONF_SUB_GHZ_SNIFFER=1 \
sensniff/srf06-cc26xx \
sensniff/srf06-cc26xx:BOARD=launchpad/cc1310 \
storage/cfs-coffee/cc2538dk \
storage/cfs-coffee/openmote-cc2538 \
storage/cfs-coffee/zoul \
storage/antelope-shell/zoul \
6tisch/simple-node/zoul \
6tisch/simple-node/zoul:MAKE_WITH_ORCHESTRA=1 \
6tisch/simple-node/zoul:MAKE_WITH_SECURITY=1 \
libs/logging/zoul \
6tisch/etsi-plugtest-2017/zoul:BOARD=remote \
6tisch/etsi-plugtest-2017/srf06-cc26xx:BOARD=launchpad/cc2650 \
6tisch/6p-packet/zoul \
6tisch/sixtop/zoul \
http-socket/zoul \
libs/timers/zoul \
libs/trickle-library/zoul \
nullnet/zoul \
slip-radio/zoul \


TOOLS=

include ../Makefile.compile-test
