### Will allow the inclusion of the correct OPN makefile
DEVICE_OPN = efr32mg24b310f1536im48

BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += sl_board_default_init.c

CFLAGS += -DBOARD_CONF_PATH=\"brd2601b-conf.h\"

CONTIKI_TARGET_DIRS += brd2601b
CONTIKI_TARGET_DIRS += brd2601b/config
