MOTELIST_ZOLERTIA = remote
BOARD_SOURCEFILES += board.c antenna-sw.c mmc-arch.c rtcc.c leds-res-arch.c power-mgmt.c

MODULES += lib/fs/fat lib/fs/fat/option drivers/platform/zoul/fs/fat drivers/dev/disk/mmc
