CONTIKI_ARM_DIRS += cortex-m cortex-m/CMSIS

### Build syscalls for newlib
MODULES += os/lib/newlib

CUSTOM_RULE_LINK = 1

.SECONDEXPANSION:

%.elf: $(CPU_STARTFILES) $$(CONTIKI_OBJECTFILES) %.o $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) $(LDSCRIPT) $(TARGET_LIBS)
	$(TRACE_LD)
	$(Q)$(LD) $(LDFLAGS) ${filter-out $(LDSCRIPT) %.a,$^} ${filter %.a,$^} $(TARGET_LIBFLAGS) -o $@

include $(CONTIKI)/arch/cpu/arm/Makefile.arm
