/*
 * Copyright (c) 2013, Institute for Pervasive Computing, ETH Zurich
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the Institute nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * This file is part of the Contiki operating system.
 */

/**
 * \file
 *      Collection of constants specified in the CoAP standard.
 * \author
 *      Matthias Kovatsch <kovatsch@inf.ethz.ch>
 */

/**
 * \addtogroup coap
 * @{
 */

#ifndef COAP_CONSTANTS_H_
#define COAP_CONSTANTS_H_

#define COAP_DEFAULT_PORT                    5683
#define COAP_DEFAULT_SECURE_PORT             5684

#define COAP_DEFAULT_MAX_AGE                 60
#define COAP_RESPONSE_TIMEOUT                3
#define COAP_RESPONSE_RANDOM_FACTOR          1.5
#define COAP_MAX_RETRANSMIT                  4

#define COAP_HEADER_LEN                      4  /* | version:0x03 type:0x0C tkl:0xF0 | code | mid:0x00FF | mid:0xFF00 | */
#define COAP_TOKEN_LEN                       8  /* The maximum number of bytes for the Token */
#define COAP_ETAG_LEN                        8  /* The maximum number of bytes for the ETag */

#define COAP_HEADER_VERSION_MASK             0xC0
#define COAP_HEADER_VERSION_POSITION         6
#define COAP_HEADER_TYPE_MASK                0x30
#define COAP_HEADER_TYPE_POSITION            4
#define COAP_HEADER_TOKEN_LEN_MASK           0x0F
#define COAP_HEADER_TOKEN_LEN_POSITION       0

#define COAP_HEADER_OPTION_DELTA_MASK        0xF0
#define COAP_HEADER_OPTION_SHORT_LENGTH_MASK 0x0F

/* CoAP message types */
typedef enum {
  COAP_TYPE_CON,                /* confirmables */
  COAP_TYPE_NON,                /* non-confirmables */
  COAP_TYPE_ACK,                /* acknowledgements */
  COAP_TYPE_RST                 /* reset */
} coap_message_type_t;

/* CoAP request method codes */
typedef enum {
  COAP_GET = 1,
  COAP_POST,
  COAP_PUT,
  COAP_DELETE
} coap_method_t;

/* CoAP response codes */
typedef enum {
  NO_ERROR = 0,

  CREATED_2_01 = 65,            /* CREATED */
  DELETED_2_02 = 66,            /* DELETED */
  VALID_2_03 = 67,              /* NOT_MODIFIED */
  CHANGED_2_04 = 68,            /* CHANGED */
  CONTENT_2_05 = 69,            /* OK */
  CONTINUE_2_31 = 95,           /* CONTINUE */

  BAD_REQUEST_4_00 = 128,       /* BAD_REQUEST */
  UNAUTHORIZED_4_01 = 129,      /* UNAUTHORIZED */
  BAD_OPTION_4_02 = 130,        /* BAD_OPTION */
  FORBIDDEN_4_03 = 131,         /* FORBIDDEN */
  NOT_FOUND_4_04 = 132,         /* NOT_FOUND */
  METHOD_NOT_ALLOWED_4_05 = 133,        /* METHOD_NOT_ALLOWED */
  NOT_ACCEPTABLE_4_06 = 134,    /* NOT_ACCEPTABLE */
  PRECONDITION_FAILED_4_12 = 140,       /* BAD_REQUEST */
  REQUEST_ENTITY_TOO_LARGE_4_13 = 141,  /* REQUEST_ENTITY_TOO_LARGE */
  UNSUPPORTED_MEDIA_TYPE_4_15 = 143,    /* UNSUPPORTED_MEDIA_TYPE */

  INTERNAL_SERVER_ERROR_5_00 = 160,     /* INTERNAL_SERVER_ERROR */
  NOT_IMPLEMENTED_5_01 = 161,   /* NOT_IMPLEMENTED */
  BAD_GATEWAY_5_02 = 162,       /* BAD_GATEWAY */
  SERVICE_UNAVAILABLE_5_03 = 163,       /* SERVICE_UNAVAILABLE */
  GATEWAY_TIMEOUT_5_04 = 164,   /* GATEWAY_TIMEOUT */
  PROXYING_NOT_SUPPORTED_5_05 = 165,    /* PROXYING_NOT_SUPPORTED */

  /* Erbium errors */
  MEMORY_ALLOCATION_ERROR = 192,
  PACKET_SERIALIZATION_ERROR,

  /* Erbium hooks */
  MANUAL_RESPONSE,
  PING_RESPONSE
} coap_status_t;

/* CoAP header option numbers */
typedef enum coap_option_t {
  /* Autogenerated IANA CoAP Option Numbers (Source: https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#option-numbers) */

  /* 0-255 : IETF Review or IESG Approval */
  // If-Match; Ref: [RFC7252][RFC8613]
  COAP_OPTION_IF_MATCH = 1,
  // Uri-Host; Ref: [RFC7252][RFC8613]
  COAP_OPTION_URI_HOST = 3,
  // ETag; Ref: [RFC7252][RFC8613]
  COAP_OPTION_ETAG = 4,
  // If-None-Match; Ref: [RFC7252][RFC8613]
  COAP_OPTION_IF_NONE_MATCH = 5,
  // Observe; Ref: [RFC7641][RFC8613]
  COAP_OPTION_OBSERVE = 6,
  // Uri-Port; Ref: [RFC7252][RFC8613]
  COAP_OPTION_URI_PORT = 7,
  // Location-Path; Ref: [RFC7252][RFC8613]
  COAP_OPTION_LOCATION_PATH = 8,
  // OSCORE; Ref: [RFC8613]
  COAP_OPTION_OSCORE = 9,
  // Uri-Path; Ref: [RFC7252][RFC8613]
  COAP_OPTION_URI_PATH = 11,
  // Content-Format; Ref: [RFC7252][RFC8613]
  COAP_OPTION_CONTENT_FORMAT = 12,
  // Max-Age; Ref: [RFC7252][RFC8516][RFC8613]
  COAP_OPTION_MAX_AGE = 14,
  // Uri-Query; Ref: [RFC7252][RFC8613]
  COAP_OPTION_URI_QUERY = 15,
  // Hop-Limit; Ref: [RFC8768]
  COAP_OPTION_HOP_LIMIT = 16,
  // Accept; Ref: [RFC7252][RFC8613]
  COAP_OPTION_ACCEPT = 17,
  // Q-Block1; Ref: [RFC9177]
  COAP_OPTION_Q_BLOCK1 = 19,
  // Location-Query; Ref: [RFC7252][RFC8613]
  COAP_OPTION_LOCATION_QUERY = 20,
  // EDHOC; Ref: [RFC9668]
  COAP_OPTION_EDHOC = 21,
  // Block2; Ref: [RFC7959][RFC8323][RFC8613]
  COAP_OPTION_BLOCK2 = 23,
  // Block1; Ref: [RFC7959][RFC8323][RFC8613]
  COAP_OPTION_BLOCK1 = 27,
  // Size2; Ref: [RFC7959][RFC8613]
  COAP_OPTION_SIZE2 = 28,
  // Q-Block2; Ref: [RFC9177]
  COAP_OPTION_Q_BLOCK2 = 31,
  // Proxy-Uri; Ref: [RFC7252][RFC8613]
  COAP_OPTION_PROXY_URI = 35,
  // Proxy-Scheme; Ref: [RFC7252][RFC8613]
  COAP_OPTION_PROXY_SCHEME = 39,
  // Size1; Ref: [RFC7252][RFC8613]
  COAP_OPTION_SIZE1 = 60,
  // Echo; Ref: [RFC9175]
  COAP_OPTION_ECHO = 252,

  /* 256-2047 : Specification Required */
  // No-Response; Ref: [RFC7967][RFC8613]
  COAP_OPTION_NO_RESPONSE = 258,
  // Request-Tag; Ref: [RFC9175]
  COAP_OPTION_REQUEST_TAG = 292,

  /* 2048-64999 : Expert Review */
  // OCF-Accept-Content-Format-Version; Ref: [Michael_Koster]
  COAP_OPTION_OCF_ACCEPT_CONTENT_FORMAT_VERSION = 2049,
  // OCF-Content-Format-Version; Ref: [Michael_Koster]
  COAP_OPTION_OCF_CONTENT_FORMAT_VERSION = 2053,
  // SCP82-Params; Ref: [GPC_SPE_207]
  COAP_OPTION_SCP82_PARAMS = 2055

  /* 65000-65535 : Experimental use (no operational use) */
} coap_option_t;

/* CoAP Content-Formats */
typedef enum coap_content_format_t {
  /* Autogenerated IANA CoAP Content-Formats (Source: https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats) */

  /* 0-255 : Expert Review */
  // text/plain; charset=utf-8; Ref: [RFC2046][RFC3676][RFC5147]
  COAP_CONTENT_FORMAT_TEXT_PLAIN_UTF_8 = 0,
  TEXT_PLAIN = 0 /* depreciated but identifier kept for backwards compatibility */,
  TEXT_XML = 1,
  TEXT_CSV = 2,
  TEXT_HTML = 3,
  // application/cose; cose-type="cose-encrypt0"; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_ENCRYPT0 = 16,
  // application/cose; cose-type="cose-mac0"; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_MAC0 = 17,
  // application/cose; cose-type="cose-sign1"; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_SIGN1 = 18,
  // application/ace+cbor; Ref: [RFC9200]
  COAP_CONTENT_FORMAT_APPLICATION_ACE_AS_CBOR = 19,
  // image/gif; Ref: [https://www.w3.org/Graphics/GIF/spec-gif89a.txt]
  COAP_CONTENT_FORMAT_IMAGE_GIF = 21,
  IMAGE_GIF = 21 /* depreciated but identifier kept for backwards compatibility */,
  // image/jpeg; Ref: [ISO/IEC 10918-5]
  COAP_CONTENT_FORMAT_IMAGE_JPEG = 22,
  IMAGE_JPEG = 22 /* depreciated but identifier kept for backwards compatibility */,
  // image/png; Ref: [RFC2083]
  COAP_CONTENT_FORMAT_IMAGE_PNG = 23,
  IMAGE_PNG = 23 /* depreciated but identifier kept for backwards compatibility */,
  IMAGE_TIFF = 24,
  AUDIO_RAW = 25,
  VIDEO_RAW = 26,
  // application/link-format; Ref: [RFC6690]
  COAP_CONTENT_FORMAT_APPLICATION_LINK_FORMAT = 40,
  APPLICATION_LINK_FORMAT = 40 /* depreciated but identifier kept for backwards compatibility */,
  // application/xml; Ref: [RFC3023]
  COAP_CONTENT_FORMAT_APPLICATION_XML = 41,
  APPLICATION_XML = 41 /* depreciated but identifier kept for backwards compatibility */,
  // application/octet-stream; Ref: [RFC2045][RFC2046]
  COAP_CONTENT_FORMAT_APPLICATION_OCTET_STREAM = 42,
  APPLICATION_OCTET_STREAM = 42 /* depreciated but identifier kept for backwards compatibility */,
  APPLICATION_RDF_XML = 43,
  APPLICATION_SOAP_XML = 44,
  APPLICATION_ATOM_XML = 45,
  APPLICATION_XMPP_XML = 46,
  // application/exi; Ref: ["Efficient XML Interchange (EXI) Format 1.0 (Second Edition)", February 2014]
  COAP_CONTENT_FORMAT_APPLICATION_EXI = 47,
  APPLICATION_EXI = 47 /* depreciated but identifier kept for backwards compatibility */,
  APPLICATION_FASTINFOSET = 48,
  APPLICATION_SOAP_FASTINFOSET = 49,
  // application/json; Ref: [RFC8259]
  COAP_CONTENT_FORMAT_APPLICATION_JSON = 50,
  APPLICATION_JSON = 50 /* depreciated but identifier kept for backwards compatibility */,
  // application/json-patch+json; Ref: [RFC6902]
  COAP_CONTENT_FORMAT_APPLICATION_JSON_PATCH_AS_JSON = 51,
  APPLICATION_X_OBIX_BINARY = 51 /* depreciated but identifier kept for backwards compatibility */,
  // application/merge-patch+json; Ref: [RFC7396]
  COAP_CONTENT_FORMAT_APPLICATION_MERGE_PATCH_AS_JSON = 52,
  // application/cbor; Ref: [RFC8949]
  COAP_CONTENT_FORMAT_APPLICATION_CBOR = 60,
  APPLICATION_CBOR = 60 /* depreciated but identifier kept for backwards compatibility */,
  // application/cwt; Ref: [RFC8392]
  COAP_CONTENT_FORMAT_APPLICATION_CWT = 61,
  // application/multipart-core; Ref: [RFC8710]
  COAP_CONTENT_FORMAT_APPLICATION_MULTIPART_CORE = 62,
  // application/cbor-seq; Ref: [RFC8742]
  COAP_CONTENT_FORMAT_APPLICATION_CBOR_SEQ = 63,
  // application/edhoc+cbor-seq; Ref: [RFC9528]
  COAP_CONTENT_FORMAT_APPLICATION_EDHOC_AS_CBOR_SEQ = 64,
  // application/cid-edhoc+cbor-seq; Ref: [RFC9528]
  COAP_CONTENT_FORMAT_APPLICATION_CID_EDHOC_AS_CBOR_SEQ = 65,
  // application/cose; cose-type="cose-encrypt"; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_ENCRYPT = 96,
  // application/cose; cose-type="cose-mac"; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_MAC = 97,
  // application/cose; cose-type="cose-sign"; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_SIGN = 98,
  // application/cose-key; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_KEY = 101,
  // application/cose-key-set; Ref: [RFC9052]
  COAP_CONTENT_FORMAT_APPLICATION_COSE_KEY_SET = 102,
  // application/senml+json; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENML_AS_JSON = 110,
  // application/sensml+json; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENSML_AS_JSON = 111,
  // application/senml+cbor; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENML_AS_CBOR = 112,
  // application/sensml+cbor; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENSML_AS_CBOR = 113,
  // application/senml-exi; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENML_EXI = 114,
  // application/sensml-exi; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENSML_EXI = 115,
  // application/yang-data+cbor; id=sid; Ref: [RFC9254]
  COAP_CONTENT_FORMAT_APPLICATION_YANG_DATA_AS_CBOR_SID = 140,

  /* 256-9999 : IETF Review or IESG Approval */
  // application/coap-group+json; Ref: [RFC7390]
  COAP_CONTENT_FORMAT_APPLICATION_COAP_GROUP_AS_JSON = 256,
  // application/concise-problem-details+cbor; Ref: [RFC9290]
  COAP_CONTENT_FORMAT_APPLICATION_CONCISE_PROBLEM_DETAILS_AS_CBOR = 257,
  // application/swid+cbor; Ref: [RFC9393]
  COAP_CONTENT_FORMAT_APPLICATION_SWID_AS_CBOR = 258,
  // application/pkixcmp; Ref: [RFC9482][RFC-ietf-lamps-rfc6712bis-10]
  COAP_CONTENT_FORMAT_APPLICATION_PKIXCMP = 259,
  // application/yang-sid+json; Ref: [RFC9595]
  COAP_CONTENT_FORMAT_APPLICATION_YANG_SID_AS_JSON = 260,
  // application/ace-groupcomm+cbor; Ref: [RFC9594]
  COAP_CONTENT_FORMAT_APPLICATION_ACE_GROUPCOMM_AS_CBOR = 261,
  // application/ace-trl+cbor; Ref: [RFC-ietf-ace-revoked-token-notification-09]
  COAP_CONTENT_FORMAT_APPLICATION_ACE_TRL_AS_CBOR = 262,
  // application/eat+cwt; Ref: [RFC-ietf-rats-eat-media-type-12]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_AS_CWT = 263,
  // application/eat+jwt; Ref: [RFC-ietf-rats-eat-media-type-12]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_AS_JWT = 264,
  // application/eat-bun+cbor; Ref: [RFC-ietf-rats-eat-media-type-12]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_BUN_AS_CBOR = 265,
  // application/eat-bun+json; Ref: [RFC-ietf-rats-eat-media-type-12]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_BUN_AS_JSON = 266,
  // application/eat-ucs+cbor; Ref: [RFC-ietf-rats-eat-media-type-12]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_UCS_AS_CBOR = 267,
  // application/eat-ucs+json; Ref: [RFC-ietf-rats-eat-media-type-12]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_UCS_AS_JSON = 268,
  // application/dots+cbor; Ref: [RFC9132]
  COAP_CONTENT_FORMAT_APPLICATION_DOTS_AS_CBOR = 271,
  // application/missing-blocks+cbor-seq; Ref: [RFC9177]
  COAP_CONTENT_FORMAT_APPLICATION_MISSING_BLOCKS_AS_CBOR_SEQ = 272,
  // application/pkcs7-mime; smime-type=server-generated-key; Ref: [RFC7030][RFC8551][RFC9148]
  COAP_CONTENT_FORMAT_APPLICATION_PKCS7_MIME_SERVER_GENERATED_KEY = 280,
  // application/pkcs7-mime; smime-type=certs-only; Ref: [RFC8551][RFC9148]
  COAP_CONTENT_FORMAT_APPLICATION_PKCS7_MIME_CERTS_ONLY = 281,
  // application/pkcs8; Ref: [RFC5958][RFC8551][RFC9148]
  COAP_CONTENT_FORMAT_APPLICATION_PKCS8 = 284,
  // application/csrattrs; Ref: [RFC7030][RFC9148]
  COAP_CONTENT_FORMAT_APPLICATION_CSRATTRS = 285,
  // application/pkcs10; Ref: [RFC5967][RFC8551][RFC9148]
  COAP_CONTENT_FORMAT_APPLICATION_PKCS10 = 286,
  // application/pkix-cert; Ref: [RFC2585][RFC9148]
  COAP_CONTENT_FORMAT_APPLICATION_PKIX_CERT = 287,
  // application/aif+cbor; Ref: [RFC9237]
  COAP_CONTENT_FORMAT_APPLICATION_AIF_AS_CBOR = 290,
  // application/aif+json; Ref: [RFC9237]
  COAP_CONTENT_FORMAT_APPLICATION_AIF_AS_JSON = 291,
  // application/senml+xml; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENML_AS_XML = 310,
  // application/sensml+xml; Ref: [RFC8428]
  COAP_CONTENT_FORMAT_APPLICATION_SENSML_AS_XML = 311,
  // application/senml-etch+json; Ref: [RFC8790]
  COAP_CONTENT_FORMAT_APPLICATION_SENML_ETCH_AS_JSON = 320,
  // application/senml-etch+cbor; Ref: [RFC8790]
  COAP_CONTENT_FORMAT_APPLICATION_SENML_ETCH_AS_CBOR = 322,
  // application/yang-data+cbor; Ref: [RFC9254]
  COAP_CONTENT_FORMAT_APPLICATION_YANG_DATA_AS_CBOR = 340,
  // application/yang-data+cbor; id=name; Ref: [RFC9254]
  COAP_CONTENT_FORMAT_APPLICATION_YANG_DATA_AS_CBOR_NAME = 341,
  // application/td+json; Ref: ["Web of Things (WoT) Thing Description 1.1", April 2022]
  COAP_CONTENT_FORMAT_APPLICATION_TD_AS_JSON = 432,
  // application/tm+json; Ref: ["Web of Things (WoT) Thing Description 1.1", April 2022]
  COAP_CONTENT_FORMAT_APPLICATION_TM_AS_JSON = 433,
  // application/uccs+cbor; Ref: [RFC-ietf-rats-uccs-12, Section 6.4]
  COAP_CONTENT_FORMAT_APPLICATION_UCCS_AS_CBOR = 601,
  // application/voucher+cose (TEMPORARY - registered 2022-04-12, extension registered 2024-03-01, expires 2025-04-12); Ref: [draft-ietf-anima-constrained-voucher-23]
  COAP_CONTENT_FORMAT_APPLICATION_VOUCHER_AS_COSE = 836,

  /* 10000-64999 : First Come First Served */
  // application/vnd.ocf+cbor; Ref: [Michael_Koster]
  COAP_CONTENT_FORMAT_APPLICATION_VND_OCF_AS_CBOR = 10000,
  // application/oscore; Ref: [RFC8613]
  COAP_CONTENT_FORMAT_APPLICATION_OSCORE = 10001,
  // application/javascript; Ref: [RFC4329]
  COAP_CONTENT_FORMAT_APPLICATION_JAVASCRIPT = 10002,
  // application/eat+cwt; eat_profile="tag:psacertified.org,2023:psa#tfm"; Ref: [RFC-tschofenig-rats-psa-token-24]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_AS_CWT_TAG_PSACERTIFIED_ORG_2023_PSA_TFM = 10003,
  // application/eat+cwt; eat_profile="tag:psacertified.org,2019:psa#legacy"; Ref: [RFC-tschofenig-rats-psa-token-24]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_AS_CWT_TAG_PSACERTIFIED_ORG_2019_PSA_LEGACY = 10004,
  // application/eat+cwt; eat_profile=2.16.840.1.113741.1.16.1; Ref: [RFC-ietf-rats-eat-media-type-12][draft-cds-rats-intel-corim-profile-02]
  COAP_CONTENT_FORMAT_APPLICATION_EAT_AS_CWT_2_16_840_1_113741_1_16_1 = 10005,
  // application/toc+cbor; Ref: [CE-Binding, Section 6.3.1]
  COAP_CONTENT_FORMAT_APPLICATION_TOC_AS_CBOR = 10570,
  // application/ce+cbor; Ref: [CE-Binding, Section 6.3.2]
  COAP_CONTENT_FORMAT_APPLICATION_CE_AS_CBOR = 10571,
  // application/json; deflate; Ref: [RFC8259][RFC9110, Section 8.4.1.2]
  COAP_CONTENT_FORMAT_APPLICATION_JSON_DEFLATE = 11050,
  // application/cbor; deflate; Ref: [RFC8949][RFC9110, Section 8.4.1.2]
  COAP_CONTENT_FORMAT_APPLICATION_CBOR_DEFLATE = 11060,
  // application/vnd.oma.lwm2m+tlv; Ref: [OMA-TS-LightweightM2M-V1_0]
  COAP_CONTENT_FORMAT_APPLICATION_VND_OMA_LWM2M_AS_TLV = 11542,
  // application/vnd.oma.lwm2m+json; Ref: [OMA-TS-LightweightM2M-V1_0]
  COAP_CONTENT_FORMAT_APPLICATION_VND_OMA_LWM2M_AS_JSON = 11543,
  // application/vnd.oma.lwm2m+cbor; Ref: [OMA-TS-LightweightM2M-V1_2]
  COAP_CONTENT_FORMAT_APPLICATION_VND_OMA_LWM2M_AS_CBOR = 11544,
  // text/css; Ref: [RFC2318]
  COAP_CONTENT_FORMAT_TEXT_CSS = 20000,
  // image/svg+xml; Ref: [https://www.w3.org/TR/SVG/mimereg.html]
  COAP_CONTENT_FORMAT_IMAGE_SVG_AS_XML = 30000

  /* 65000-65535 : Experimental use (no operational use) */
} coap_content_format_t;

/**
 * Resource flags for allowed methods and special functionalities.
 */
typedef enum {
  NO_FLAGS = 0,

  /* methods to handle */
  METHOD_GET = (1 << 0),
  METHOD_POST = (1 << 1),
  METHOD_PUT = (1 << 2),
  METHOD_DELETE = (1 << 3),

  /* special flags */
  HAS_SUB_RESOURCES = (1 << 4),
  IS_SEPARATE = (1 << 5),
  IS_OBSERVABLE = (1 << 6),
  IS_PERIODIC = (1 << 7)
} coap_resource_flags_t;

#endif /* COAP_CONSTANTS_H_ */
/** @} */
