MAKE_WITH_DTLS ?= 0

ifeq ($(MAKE_WITH_DTLS),1)

 TINYDTLS_PATH := os/net/security/tinydtls

 ifeq (${wildcard $(CONTIKI)/$(TINYDTLS_PATH)/Makefile},)
  ${error Could not find the tinyDTLS submodule. Please run "git submodule update --init" and try again}
 endif

 CFLAGS += -DWITH_DTLS=1

 MODULES += os/net/app-layer/coap/tinydtls-support
 MODULES += $(TINYDTLS_PATH) ${addprefix $(TINYDTLS_PATH)/,aes sha2 ecc}

endif
