CONTIKI = ../../..

MODULES += os/storage/antelope os/services/unit-test

# does not fit on Sky
PLATFORMS_ONLY= cc2538dk zoul

CONTIKI_PROJECT = shell-db
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
