BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += board-sensors.c

CFLAGS += -DBOARD_CONF_PATH=\"nrf54l15-dk-conf.h\"
CFLAGS += -DBOARD_DEF_PATH=\"nrf54l15-dk-def.h\"

include $(PLATFORM_ROOT_DIR)/nrf54l15/Makefile.nrf54l15

CONTIKI_TARGET_DIRS += nrf54l15/dk
