EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
rpl-border-router/zoul \
platform-specific/cc2538-common/zoul \
platform-specific/cc2538-common/crypto/zoul \
platform-specific/cc2538-common/pka/zoul \
platform-specific/zoul/orion/ip64-router/zoul:BOARD=orion \
platform-specific/zoul/orion/client/zoul:BOARD=orion \
platform-specific/zoul/rev-b/zoul:BOARD=remote-revb  \
platform-specific/zoul/at-test/zoul \
platform-specific/zoul/rtcc/zoul \
platform-specific/zoul/zoul \
coap/zoul \
multicast/zoul \
ipso-objects/zoul \
ipso-objects/zoul:MAKE_WITH_DTLS=1 \
hello-world/zoul \
sensniff/zoul \
sensniff/zoul:ZOUL_CONF_SUB_GHZ_SNIFFER=1 \
storage/cfs-coffee/zoul \
storage/antelope-shell/zoul \
6tisch/simple-node/zoul \
6tisch/simple-node/zoul:MAKE_WITH_ORCHESTRA=1 \
6tisch/simple-node/zoul:MAKE_WITH_SECURITY=1 \
libs/logging/zoul \
6tisch/etsi-plugtest-2017/zoul:BOARD=remote \
6tisch/6p-packet/zoul \
6tisch/sixtop/zoul \
http-socket/zoul \
libs/timers/zoul \
libs/energest/zoul \
libs/trickle-library/zoul \
libs/data-structures/zoul \
nullnet/zoul \
slip-radio/zoul \
dev/gpio-hal/zoul:BOARD=remote-reva \
dev/gpio-hal/zoul:BOARD=remote-revb \
dev/gpio-hal/zoul:BOARD=firefly-reva \
dev/gpio-hal/zoul:BOARD=firefly \
dev/gpio-hal/zoul:BOARD=orion \
dev/leds/zoul:BOARD=remote-reva \
dev/leds/zoul:BOARD=remote-revb \
dev/leds/zoul:BOARD=firefly-reva \
dev/leds/zoul:BOARD=firefly \
dev/leds/zoul:BOARD=orion \
dev/rgb-led/zoul:BOARD=remote-reva \
dev/rgb-led/zoul:BOARD=remote-revb \
dev/rgb-led/zoul:BOARD=firefly-reva \
dev/rgb-led/zoul:BOARD=firefly \
dev/rgb-led/zoul:BOARD=orion \
mqtt-client/zoul:BOARD=firefly \
mqtt-client/openmote-cc2538 \
storage/cfs-coffee/openmote-cc2538 \
sensniff/openmote-cc2538 \
hello-world/openmote-cc2538 \
rpl-udp/openmote-cc2538 \
dev/gpio-hal/openmote-cc2538 \
dev/leds/openmote-cc2538 \
rpl-border-router/openmote-cc2538 \
ipv6-hooks/openmote-cc2538 \

TOOLS=

include ../Makefile.compile-test
