EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
rpl-border-router/zoul \
platform-specific/cc2538-common/zoul \
platform-specific/cc2538-common/mqtt-demo/zoul \
platform-specific/cc2538-common/crypto/zoul \
platform-specific/cc2538-common/pka/zoul \
platform-specific/zoul/orion/ip64-router/zoul:BOARD=orion \
coap/zoul \
ipso-objects/zoul \
hello-world/zoul \
sensniff/zoul \
sensniff/zoul:ZOUL_CONF_SUB_GHZ_SNIFFER=1 \
storage/cfs-coffee/zoul \
storage/antelope-shell/zoul \
6tisch/simple-node/zoul \
6tisch/simple-node/zoul:MAKE_WITH_ORCHESTRA=1 \
6tisch/simple-node/zoul:MAKE_WITH_SECURITY=1 \
libs/logging/zoul \
6tisch/etsi-plugtest-2017/zoul:BOARD=remote \
6tisch/6p-packet/zoul \
6tisch/sixtop/zoul \
http-socket/zoul \
libs/timers/zoul \
libs/energest/zoul \
libs/trickle-library/zoul \
nullnet/zoul \
slip-radio/zoul \
storage/cfs-coffee/openmote-cc2538 \
sensniff/openmote-cc2538 \
hello-world/openmote-cc2538 \
rpl-udp/openmote-cc2538 \
rpl-border-router/openmote-cc2538

TOOLS=

include ../Makefile.compile-test
