EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
rpl-border-router/zoul \
platform-specific/cc2538-common/zoul \
platform-specific/cc2538-common/mqtt-demo/zoul \
platform-specific/cc2538-common/crypto/zoul \
platform-specific/cc2538-common/pka/zoul \
platform-specific/zoul/orion/ip64-router/zoul:BOARD=orion \
platform-specific/zoul/rev-b/test-power-mgmt/zoul:BOARD=remote-revb  \
platform-specific/zoul/at-test/at-master-test/zoul \
platform-specific/zoul/rtcc/test-rtcc/zoul \
platform-specific/zoul/test-ac-dimmer/zoul \
platform-specific/zoul/test-motion/zoul \
platform-specific/zoul/test-grove-gyro/zoul \
platform-specific/zoul/test-vac-sensor/zoul \
platform-specific/zoul/test-grove-light-sensor/zoul \
platform-specific/zoul/test-iaq/zoul \
platform-specific/zoul/test-pm10-sensor/zoul \
platform-specific/zoul/test-sht25/zoul \
platform-specific/zoul/test-servo/zoul \
platform-specific/zoul/test-tsl256x/zoul \
platform-specific/zoul/test-zonik/zoul \
platform-specific/zoul/test-dht22/zoul \
platform-specific/zoul/test-aac-sensor/zoul \
platform-specific/zoul/test-grove-loudness-sensor/zoul \
platform-specific/zoul/test-relay/zoul \
platform-specific/zoul/test-bmp085-bmp180/zoul \
platform-specific/zoul/test-lcd/zoul \
platform-specific/zoul/test-weather-meter/zoul \
platform-specific/zoul/test-bme280/zoul \
platform-specific/zoul/test-rotation-sensor/zoul \
coap/zoul \
ipso-objects/zoul \
ipso-objects/zoul:MAKE_WITH_DTLS=1 \
hello-world/zoul \
sensniff/zoul \
sensniff/zoul:ZOUL_CONF_SUB_GHZ_SNIFFER=1 \
storage/cfs-coffee/zoul \
storage/antelope-shell/zoul \
6tisch/simple-node/zoul \
6tisch/simple-node/zoul:MAKE_WITH_ORCHESTRA=1 \
6tisch/simple-node/zoul:MAKE_WITH_SECURITY=1 \
libs/logging/zoul \
6tisch/etsi-plugtest-2017/zoul:BOARD=remote \
6tisch/6p-packet/zoul \
6tisch/sixtop/zoul \
http-socket/zoul \
libs/timers/zoul \
libs/energest/zoul \
libs/trickle-library/zoul \
libs/data-structures/zoul \
nullnet/zoul \
slip-radio/zoul \
dev/gpio-hal/zoul:BOARD=remote-reva \
dev/gpio-hal/zoul:BOARD=remote-revb \
dev/gpio-hal/zoul:BOARD=firefly-reva \
dev/gpio-hal/zoul:BOARD=firefly \
dev/gpio-hal/zoul:BOARD=orion \
storage/cfs-coffee/openmote-cc2538 \
sensniff/openmote-cc2538 \
hello-world/openmote-cc2538 \
rpl-udp/openmote-cc2538 \
dev/gpio-hal/openmote-cc2538 \
rpl-border-router/openmote-cc2538

TOOLS=

include ../Makefile.compile-test
