EXAMPLESDIR=$(HOME)/out-of-tree-tests

EXAMPLES = \
hello-world/native \
hello-world/zoul \
hello-world/openmote \
hello-world/cc26x0-cc13x0 \
hello-world/simplelink:BOARD=launchpad/cc26x2r1 \
hello-world/simplelink:BOARD=sensortag/cc2650 \

include ../Makefile.compile-test
