CONTIKI_PROJECT = edhoc-client-example
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

# Include required modules (without CONTIKI prefix like test code)
MODULES += os/net/security/edhoc

include $(CONTIKI)/Makefile.include