CFLAGS += -DBOARD_LAUNCHPAD=1

CONTIKI_TARGET_DIRS += launchpad common

BOARD_SOURCEFILES += board.c board-buttons.c xmem.c

MODULES += arch/dev/ext-flash

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
