include $(CONTIKI_CPU)/Makefile.gecko_sdk  

DEVICE_FAMILY := EFR32MG12P
RAIL_FAMILY := efr32xg12

CFLAGS += -mfpu=fpv4-sp-d16 -mfloat-abi=softfp

LDFLAGS += -mfpu=fpv4-sp-d16 -mfloat-abi=softfp

include $(CONTIKI_CPU)/Makefile.gecko

include $(CONTIKI)/$(CONTIKI_NG_CM4_DIR)/Makefile.cm4
