#ifndef _IEEE_SETTINGS_H_
#define _IEEE_SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.9.0 (build#85)
// Compatible with SimpleLink SDK version: No known SDK for this device
// Device: CC2650 Rev. 2.2
//
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
// This must be included "locally" frm the cpu directory,
// as it isn't defined in CC13x0 driverlib
#include "driverlib/rf_ieee_cmd.h"

#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode RF_ieeeMode;


// TX Power Table
extern RF_TxPowerTable_Entry ieeeTxPowerTable[14];


// RF Core API commands
extern rfc_CMD_RADIO_SETUP_t RF_cmdRadioSetup;
extern rfc_CMD_FS_t RF_cmdIeeeFs;
extern rfc_CMD_IEEE_TX_t RF_cmdIeeeTx;
extern rfc_CMD_IEEE_RX_t RF_cmdIeeeRx;


// RF Core API Overrides
extern uint32_t pIeeeOverrides[];


#endif // _IEEE_SETTINGS_H_

