#ifndef RF_PROP_SETTINGS_H_
#define RF_PROP_SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.8.0 ( build #41)
// Compatible with SimpleLink SDK version: CC13x2 SDK 1.60.xx.xx
// Device: CC1352 Rev. 1.0
//
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>

#include <rf-common.h>

// RF TX power table
extern RF_TxPower RF_propTxPower779_930[];
extern RF_TxPower RF_propTxPower431_527[];

// TI-RTOS RF Mode Object
extern RF_Mode RF_propMode;

// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t rf_cmd_prop_radio_div_setup;
extern rfc_CMD_FS_t                   rf_cmd_prop_fs;
extern rfc_CMD_PROP_TX_ADV_t          rf_cmd_prop_tx_adv;
extern rfc_CMD_PROP_RX_ADV_t          rf_cmd_prop_rx_adv;


#endif /* RF_PROP_SETTINGS_H_ */
