CONTIKI_PROJECT = edhoc-server-example
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

# Include required modules (without CONTIKI prefix like test code)
MODULES += os/net/security/edhoc
MODULES += os/net/security/edhoc/server

include $(CONTIKI)/Makefile.include