#!/usr/bin/env python3
#
# Copyright (c) 2026, RISE Research Institutes of Sweden AB
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
"""Generate flpr-blob.h from an FLPR firmware .bin.

Usage:
    python3 tools/flpr-blob-gen.py <flpr-firmware.bin> \\
        > examples/platform-specific/nrf/flpr-host/flpr-blob.h

The generated header exposes only the firmware bytes:
    flpr_blob[]           - the raw firmware bytes, 4-byte aligned
    flpr_blob_len         - byte count

The shared memory map (load/exec address, shared counter, ...) lives in
arch/cpu/nrf-vpr/shared/flpr-shared.h, the single source of truth for both cores.

Used by examples/platform-specific/nrf/flpr-host to embed the FLPR firmware in
the M33 image.
"""
import sys

data = open(sys.argv[1], 'rb').read()
print('/* Auto-generated by tools/flpr-blob-gen.py -- do not edit. */')
print('#ifndef FLPR_BLOB_H')
print('#define FLPR_BLOB_H')
print('#include <stdint.h>')
print('#include <stddef.h>')
print()
print('static const uint32_t flpr_blob_len = %u;' % len(data))
print('static const uint8_t flpr_blob[] __attribute__((aligned(4))) = {')
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    print('  ' + ', '.join('0x%02x' % b for b in chunk) + ',')
print('};')
print('#endif /* FLPR_BLOB_H */')
