EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/native \
hello-world/sky \
eeprom-test/native \
multicast/sky \
logging/native \
ipv6/rpl-udp/sky \

TOOLS=

include ../Makefile.compile-test
