EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/native \
hello-world/sky \
storage/eeprom-test/native \
multicast/sky \
libs/logging/native \
rpl-udp/sky \
native-border-router/native \
slip-radio/sky \

TOOLS=

include ../Makefile.compile-test
