### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26x0

### Add to the source dirs
CONTIKI_TARGET_DIRS += sensortag/cc2650

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/sensortag/Makefile.sensortag
