RUN_FILE = 1

EXAMPLESDIR = ./

EXAMPLES = \
code-test-lc/native:code-test-lc/test-lc-switch:test-lc-switch \
code-test-lc/native:code-test-lc/test-lc-addrlabels:test-lc-addrlabels \
code-test-memb/native:code-test-memb/test-memb \
code-result-visualization/native:./04-test-result-visualization.sh

include ../Makefile.compile-test
