ifeq ($(NS), 1)
	FLASH_START = 0x10031000
	FLASH_LENGTH = 0xCF000
	RAM_START = 0x30008000
	RAM_LENGTH =  0x38000

	CFLAGS += -DTRUSTZONE_NONSECURE
	LDFLAGS += -Wl,--defsym,ld_flash_start=$(FLASH_START),--defsym,ld_flash_length=$(FLASH_LENGTH),--defsym,ld_ram_start=$(RAM_START),--defsym,ld_ram_length=$(RAM_LENGTH)

	TARGET_LIBFILES += $(PLATFORM_ROOT_DIR)/$(BOARD)/cmse_lib.o
endif

