CONTIKI_PROJECT = button-hal-example
CONTIKI = ../../..

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY += cc26x0-cc13x0 cc2538dk openmote-cc2538 zoul simplelink
PLATFORMS_ONLY += cooja native

include $(CONTIKI)/Makefile.include
