CONTIKI_PROJECT = button-hal-example
CONTIKI = ../../..

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY += cc26x0-cc13x0 cc2538dk gecko openmote zoul simplelink nrf
PLATFORMS_ONLY += cooja native msp-exp430fr5969

include $(CONTIKI)/Makefile.include
