################################################################################
# SimpleLink LaunchPad makefile

BOARD_TYPE = BOARD_LAUNCHPAD

PLATFORM_HAS_BUTTON = 1

# leds-arch.c/h etc.
BOARD_SOURCEFILES += button-sensor-arch.c leds-arch.c

TARGET_FAMILY_DIRS += launchpad
