MOTELIST_OPPILA := OMote
CONTIKI_TARGET_SOURCEFILES += contiki-main.c adxl345.c 
CONTIKI_TARGET_SOURCEFILES += bmp180.c omote-sensors.c 
CONTIKI_TARGET_SOURCEFILES += adc-omote.c adc-sensors.c
BOARD_SOURCEFILES += board.c leds-arch.c
