EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx \
platform-specific/cc26xx/very-sleepy-demo/srf06-cc26xx:BOARD=sensortag/cc2650 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=sensortag/cc2650 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=sensortag/cc1350 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=srf06/cc13xx \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc2650 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc1310 \
platform-specific/cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc1350 \
platform-specific/cc26xx/very-sleepy-demo/srf06-cc26xx \
platform-specific/cc26xx/ble-ipv6/srf06-cc26xx:BOARD=sensortag/cc2650 \
nullnet/srf06-cc26xx:BOARD=sensortag/cc2650 \
rpl-border-router/srf06-cc26xx:BOARD=launchpad/cc2650 \
sensniff/srf06-cc26xx \
sensniff/srf06-cc26xx:BOARD=launchpad/cc1310 \
dev/gpio-hal/srf06-cc26xx:BOARD=srf06/cc13xx \
dev/gpio-hal/srf06-cc26xx:BOARD=srf06/cc26xx \
dev/gpio-hal/srf06-cc26xx:BOARD=sensortag/cc1350 \
dev/gpio-hal/srf06-cc26xx:BOARD=sensortag/cc2650 \
dev/gpio-hal/srf06-cc26xx:BOARD=launchpad/cc1310 \
dev/gpio-hal/srf06-cc26xx:BOARD=launchpad/cc1350 \
dev/gpio-hal/srf06-cc26xx:BOARD=launchpad/cc2650 \
dev/leds/srf06-cc26xx:BOARD=srf06/cc13xx \
dev/leds/srf06-cc26xx:BOARD=srf06/cc26xx \
dev/leds/srf06-cc26xx:BOARD=sensortag/cc1350 \
dev/leds/srf06-cc26xx:BOARD=sensortag/cc2650 \
dev/leds/srf06-cc26xx:BOARD=launchpad/cc1310 \
dev/leds/srf06-cc26xx:BOARD=launchpad/cc1350 \
dev/leds/srf06-cc26xx:BOARD=launchpad/cc2650 \
6tisch/etsi-plugtest-2017/srf06-cc26xx:BOARD=launchpad/cc2650 \
mqtt-client/srf06-cc26xx:BOARD=srf06/cc26xx \
mqtt-client/srf06-cc26xx:BOARD=launchpad/cc2650 \
mqtt-client/srf06-cc26xx:BOARD=sensortag/cc2650 \
mqtt-client/cc2538dk \
storage/cfs-coffee/cc2538dk \
sensniff/cc2538dk \
rpl-udp/cc2538dk \
coap/cc2538dk \
slip-radio/cc2538dk \
ipso-objects/cc2538dk \
multicast/cc2538dk \
dev/gpio-hal/cc2538dk \
dev/leds/cc2538dk \
platform-specific/cc2538-common/cc2538dk \
platform-specific/cc2538-common/crypto/cc2538dk \
platform-specific/cc2538-common/pka/cc2538dk \
hello-world/cc2538dk \
rpl-border-router/cc2538dk \
rpl-border-router/cc2538dk:MAKE_ROUTING=MAKE_ROUTING_RPL_CLASSIC \
hello-world/nrf52dk \
platform-specific/nrf52dk/coap-demo/coap-server/nrf52dk \
platform-specific/nrf52dk/coap-demo/coap-client/nrf52dk:SERVER_IPV6_EP=ffff \
platform-specific/nrf52dk/mqtt-demo/nrf52dk \
platform-specific/nrf52dk/blink-hello/nrf52dk \
platform-specific/nrf52dk/timer-test/nrf52dk \
libs/data-structures/nrf52dk \
libs/logging/nrf52dk

TOOLS=

include ../Makefile.compile-test
